### PR TITLE
fix bug and client add etcd

### PR DESCRIPTION
**Pull request by liuquanliang520**

### CODE REVIEW

**Comment by XavierGeerinck** [comment]
@xizhibei can this one be merged? It solves a bug as well in the Service Definition

**Comment by xizhibei** [comment]
@thebillkidy This pr decreased coverage, I can't merge it now.

But could you file an new issue to show the detail of the bug you encountered? And test cases would be better.

**Comment by XavierGeerinck** [comment]
@tony-liuql could you split the PR in 2 different issues or fix test coverage for this bug to be implemented?

@xizhibei in short, it seems that the code requires a multi dimensional object, but there is only 1 dimension being defined (rather than pkg -> svg it should be pkg.svc as the key). See: https://github.com/xizhibei/grpc-helper/pull/9/files#diff-3cafb86a5b0a9d0916a7fed543a1fb53

**Comment by xizhibei** [comment]
@thebillkidy It was fixed is the new release v0.5.1, check it out: https://github.com/xizhibei/grpc-helper/releases

**Comment by xizhibei** [comment]
Reopen it if you fixed coverage problem

**Pull request closed without merging**
